Revised readme file and added two logo pictures
vishu-tyagi/JNJ-Capstone-Project pull request #4
Opened 2022-10-03 19:42 UTC by yiiihao

Added pic folder with two logo pictures and revised readme file as required on coursework. Please check the content. Unable to make the two logos side by side (works fine locally but cannot display properly on github).

2022-10-03 20:20 UTC, vishu-tyagi commented on README.md
> -```
I think we should keep the setup instructions as they are, just move them below the project description.

2022-10-03 20:21 UTC, vishu-tyagi commented on README.md
> +- Build metrics to evaluate the model and benmark using other available large language models as well as traditional machine learning models.
Typo here: benmark should be benchmark

2022-10-03 20:23 UTC, vishu-tyagi commented on README.md
> +  <img src="pic/columbia_dsi_logo.png" width='300'/>
Looks great

2022-10-03 20:24 UTC, vishu-tyagi commented on README.md
> +<img src="pic/Johnson-Johnson-Logo.png" alt="image" title="Text to show on mouseover" width='270'/> <img src="pic/columbia_dsi_logo.png" alt="image" title="Text to show on mouseover" width="270"  />
Nice idea to add logos

2022-10-03 20:24 UTC, vishu-tyagi commented on README.md
> +- Build metrics to evaluate the model and benmark using other available large language models as well as traditional machine learning models.
Content looks great

2022-10-03 20:30 UTC, vishu-tyagi requested changes
Hi Yihao. I've left two comments that require your attention. One regarding setup instructions on the readme file and other about a slight typo. 

Also, I think it might be a good idea to keep images in /notebooks/images/ rather than at the top level directory. Could you please move the images from /pic/ to /notebooks/images/?

2022-10-03 22:00 UTC, yiiihao commented on README.md
> +- Build metrics to evaluate the model and benmark using other available large language models as well as traditional machine learning models.
Fixed typo

2022-10-03 22:02 UTC, yiiihao commented on README.md
> -```
Yes. Added setup instructions.

2022-10-03 22:11 UTC, yiiihao commented
Added setup instructions below the project description, fixed typo, moved images to notebooks/images/.

2022-10-03 23:23 UTC, vishu-tyagi approved these changes

2022-10-04 14:44 UTC, siwenxie919 approved these changes
Good job!

2022-10-04 21:26 UTC, merged